#DOMANIN REFERENCES
domain: "https://ph4ge.blog.myopic.one"
baseurl: "/"
url: "https://ph4ge.blog.myopic.one"

#TITLES AND REFERNCES
title: PH4GE's Blog
name: PH4GE's Blog
email: ph4ge@tutanota.com
description: >- # this means to ignore newlines until
  An esoteric collection of musings, art, projects and scribbles created
  by a lone idiot.

#LOGO FILE
logo: bacto-banner.png

# BUILD SETTINGS
remote_theme: b2a3e8/jekyll-theme-console
permalink: /:categories/:title/
plugins:
  - jekyll-feed

# THEME SPECIFIC
style: ocean
listen_for_clients_preferred_style: true
header_pages:
  - index.md
  - categories.md
  - about.md
footer: 'PH4GE - find me on <a rel="me" href="https://myopic.one/web/@PH4GE">Mastodon</a>'
rss: 'rss'